---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning = FALSE)
library(tidyverse)
library(timevis)
db <- read_csv("db.csv")
db  %>% 
  mutate(imprison = lubridate::dmy(imprison),
         clause = str_replace_all(clause, ";", "<br>"),
         content = str_c(name, 
                         " ",
                         second_name, 
                         " ",
                         last_name, 
                         " (", 
                         born,
                         ") <br>",
                         clause)) %>% 
  rename(start = imprison) ->
  for_timeline
```

###  {.tabset .tabset-fade .tabset-pills}

####  Timeline {.tabset .tabset-fade .tabset-pills}

##### Без группировки
```{r}
timevis(for_timeline, showZoom = TRUE, fit = TRUE)
```


##### По делу
```{r}
db %>% 
  distinct(content = case,
           id = as.numeric(factor(case))) ->
  groups_case

for_timeline %>% 
  mutate(group = as.numeric(factor(case))) %>% 
  timevis(showZoom = TRUE, fit = TRUE, groups = groups_case)
```

##### По полу
```{r}
db %>% 
  distinct(content = gender,
           id = as.numeric(factor(gender))) ->
  groups_gender

for_timeline %>% 
  mutate(group = as.numeric(factor(gender))) %>% 
  timevis(showZoom = TRUE, fit = TRUE, groups = groups_gender)
```

##### По типу заключения
```{r}
db %>% 
  distinct(content = imprison_type,
           id = as.numeric(factor(imprison_type))) ->
  groups_imprison_type

for_timeline %>% 
  mutate(group = as.numeric(factor(imprison_type))) %>% 
  timevis(showZoom = TRUE, fit = TRUE, groups = groups_imprison_type)
```


####  Database

```{r}
DT::datatable(db, filter = 'top', rownames = FALSE, options = list(autoWidth = FALSE), escape = FALSE)
```

